resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
    - repository: Shared
      name: kritikos-io/.config
      type: github
      endpoint: kritikos-io
      ref: master

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - bugfix/*
      - release/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*


stages:
  - stage: SetUp
    jobs:
      - job: Versioning
        steps:
        - template: ci\templates\generic-02-versioning.yml@Shared
  - stage: Debug
    jobs:
      - job: test
        steps:
          - template: ci\templates\generic-01-debug.yml@Shared
