resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
    - repository: Shared
      name: kritikos-io/.config
      type: github
      ref: master

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - bugfix/*
      - release/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*
