resources:
  repositories:
    - repository: self
      checkoutOptions:
        submodules: true
        lfs: true
    - repository: Shared
      name: kritikos-io/.config
      type: github
      endpoint: kritikos-io
      ref: master

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - bugfix/*
      - release/*
  paths:
    include:
      - azure-pipelines.yml
      - src/*
      - tests/*

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

stages:
  - template: ci\stages\semver.yml@Shared
  - template: ci\stages\debug.yml@Shared
